/**
 * PDF Export Module
 *
 * Uses jsPDF to generate a downloadable PDF of the shutter plan.
 */

const ShutterPDF = (() => {

  function generate(plan) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'letter' });
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    const margin = 50;
    const contentW = pw - 2 * margin;
    let y = margin;

    const cfg = plan.config;
    const geo = plan.geometry;

    // ── Title ──
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Shutter Design Plan', pw / 2, y, { align: 'center' });
    y += 30;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120);
    doc.text('Generated by Shutter Design Wizard (offline archive)', pw / 2, y, { align: 'center' });
    y += 8;
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pw / 2, y, { align: 'center' });
    doc.setTextColor(0);
    y += 25;

    // ── Summary ──
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Configuration Summary', margin, y);
    y += 18;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const typeLabels = {
      'fixed': 'Fixed',
      'movable-front': 'Movable (Front Control Arm)',
      'movable-hidden': 'Movable (Hidden Control Arm)',
    };

    const summaryLines = [
      `Louver Size: ${ShutterCalc.frac(cfg.louverSize)}`,
      `Louver Type: ${typeLabels[cfg.louverType] || cfg.louverType}`,
      `Panel Dimensions: ${ShutterCalc.frac(cfg.panelWidth)} W x ${ShutterCalc.frac(cfg.panelHeight)} H`,
      `Number of Panels: ${cfg.numPanels}`,
      `Total Louvers per Panel: ${geo.numLouvers}`,
      `Louver Spacing: ${ShutterCalc.frac(geo.louverSpacing)} on center`,
      `Joinery: ${cfg.joinery === 'dowel' ? 'Dowel / Loose Tenon' : 'Mortise & Tenon'}`,
      `Wood Species: ${cfg.woodSpecies.charAt(0).toUpperCase() + cfg.woodSpecies.slice(1)}`,
      `Frame Stock Thickness: ${ShutterCalc.frac(cfg.stockThickness)}`,
      cfg.middleRail ? 'Middle Rail: Yes' : 'Middle Rail: No',
    ];

    if (cfg.louverType !== 'fixed' && geo.controlArmLength) {
      summaryLines.push(`Control Arm Length: ${ShutterCalc.frac(geo.controlArmLength)}`);
    }

    for (const line of summaryLines) {
      doc.text(line, margin + 10, y);
      y += 14;
    }

    y += 10;

    // ── Elevation Drawing ──
    y = addSectionHeader(doc, 'Elevation Drawing', margin, y);

    // Render elevation to an offscreen canvas, then embed as image
    const elevCanvas = document.createElement('canvas');
    elevCanvas.width = 500;
    elevCanvas.height = 700;
    ShutterDrawing.drawElevation(elevCanvas, plan);
    const elevImg = elevCanvas.toDataURL('image/png');

    const imgW = contentW * 0.7;
    const imgH = imgW * (700 / 500);

    // Check if we need a new page
    if (y + imgH + 20 > ph - margin) {
      doc.addPage();
      y = margin;
      y = addSectionHeader(doc, 'Elevation Drawing', margin, y);
    }

    doc.addImage(elevImg, 'PNG', margin + (contentW - imgW) / 2, y, imgW, imgH);
    y += imgH + 15;

    // ── Cross-Section ──
    doc.addPage();
    y = margin;
    y = addSectionHeader(doc, 'Cross-Section Detail', margin, y);

    const csCanvas = document.createElement('canvas');
    csCanvas.width = 500;
    csCanvas.height = 300;
    ShutterDrawing.drawCrossSection(csCanvas, plan);
    const csImg = csCanvas.toDataURL('image/png');

    const csImgW = contentW * 0.75;
    const csImgH = csImgW * (300 / 500);
    doc.addImage(csImg, 'PNG', margin + (contentW - csImgW) / 2, y, csImgW, csImgH);
    y += csImgH + 20;

    // ── Cutting List ──
    y = addSectionHeader(doc, 'Cutting List', margin, y);
    y = drawTable(doc, margin, y, contentW,
      ['Part', 'Qty', 'Width', 'Length', 'Thickness', 'Notes'],
      [0.22, 0.07, 0.12, 0.12, 0.12, 0.35],
      plan.cuttingList.map(item => [
        item.part, String(item.qty), item.width, item.length, item.thickness, item.notes,
      ])
    );

    y += 15;

    // ── Hardware List ──
    if (y + 100 > ph - margin) {
      doc.addPage();
      y = margin;
    }
    y = addSectionHeader(doc, 'Hardware & Supplies', margin, y);
    y = drawTable(doc, margin, y, contentW,
      ['Item', 'Qty', 'Notes'],
      [0.3, 0.1, 0.6],
      plan.hardwareList.map(item => [
        item.item, String(item.qty), item.notes,
      ])
    );

    y += 15;

    // ── Construction Notes ──
    if (y + 120 > ph - margin) {
      doc.addPage();
      y = margin;
    }
    y = addSectionHeader(doc, 'Construction Notes', margin, y);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    for (const note of plan.notes) {
      const lines = doc.splitTextToSize(`\u2022 ${note}`, contentW - 10);
      if (y + lines.length * 12 > ph - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(lines, margin + 10, y);
      y += lines.length * 12 + 4;
    }

    // ── Pin Hole Schedule ──
    doc.addPage();
    y = margin;
    y = addSectionHeader(doc, 'Pin Hole Schedule (from top of stile)', margin, y);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const pinCols = [];
    for (let i = 0; i < geo.pinPositions.length; i++) {
      pinCols.push([`Louver ${i + 1}`, ShutterCalc.frac(geo.pinPositions[i])]);
    }

    y = drawTable(doc, margin, y, contentW * 0.5,
      ['Louver #', 'Distance from Top'],
      [0.4, 0.6],
      pinCols
    );

    // Footer on each page
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(150);
      doc.text(
        `Shutter Design Wizard | Page ${i} of ${totalPages}`,
        pw / 2, ph - 25, { align: 'center' }
      );
      doc.setTextColor(0);
    }

    // Save
    const filename = `shutter-plan-${cfg.panelWidth}x${cfg.panelHeight}-${cfg.louverSize}in.pdf`;
    doc.save(filename);
  }

  // ── Helpers ──

  function addSectionHeader(doc, title, x, y) {
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(title, x, y);
    y += 5;
    doc.setDrawColor(44, 95, 45);
    doc.setLineWidth(1.5);
    doc.line(x, y, x + 150, y);
    doc.setDrawColor(0);
    return y + 15;
  }

  function drawTable(doc, x, startY, tableW, headers, colRatios, rows) {
    const rowH = 16;
    const headerH = 18;
    let y = startY;
    const ph = doc.internal.pageSize.getHeight();
    const margin = 50;

    // Column positions
    const colX = [];
    const colW = [];
    let cx = x;
    for (let i = 0; i < headers.length; i++) {
      colX.push(cx);
      colW.push(tableW * colRatios[i]);
      cx += tableW * colRatios[i];
    }

    // Header
    doc.setFillColor(44, 95, 45);
    doc.rect(x, y, tableW, headerH, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255);
    for (let i = 0; i < headers.length; i++) {
      doc.text(headers[i], colX[i] + 4, y + 12);
    }
    doc.setTextColor(0);
    y += headerH;

    // Rows
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    for (let r = 0; r < rows.length; r++) {
      if (y + rowH > ph - margin) {
        doc.addPage();
        y = margin;
        // Redraw header
        doc.setFillColor(44, 95, 45);
        doc.rect(x, y, tableW, headerH, 'F');
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255);
        for (let i = 0; i < headers.length; i++) {
          doc.text(headers[i], colX[i] + 4, y + 12);
        }
        doc.setTextColor(0);
        y += headerH;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
      }

      // Zebra striping
      if (r % 2 === 0) {
        doc.setFillColor(245, 241, 235);
        doc.rect(x, y, tableW, rowH, 'F');
      }

      for (let i = 0; i < rows[r].length; i++) {
        const cellText = doc.splitTextToSize(rows[r][i] || '', colW[i] - 8);
        doc.text(cellText[0] || '', colX[i] + 4, y + 11);
      }

      // Row border
      doc.setDrawColor(220);
      doc.setLineWidth(0.3);
      doc.line(x, y + rowH, x + tableW, y + rowH);

      y += rowH;
    }

    return y;
  }

  return { generate };

})();
